name: React CI/CD

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # ✅ Install dependencies
      - name: Install dependencies
        run: npm install

      # ✅ Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # ✅ Build production app
      - name: Build React App
        run: npm run build

      # ✅ Upload build folder as artifact
      - name: Upload production build
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # ✅ Download build artifact from previous job
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: build

      # ✅ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages

